name: bot

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  start:
    runs-on: ubuntu-latest
    env:
      YUNO: ${{secrets.YUNO}}
      GH_TOKEN: ${{secrets.GH_TOKEN}}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Logging bot
      run: |
        git config --global user.name "hakureii"
        git config --global user.email "hakurei@asia.com"
        bash scripts/main.sh

