name: bot

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Logging bot
      run: |
        git config --global pull.rebase true
        while true
        do
          YUNO=${{secrets.YUNO}} PIYUNO=${{secrets.PIYUNO}} python3 bot.py
          git pull
        done

