name: bot

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  start:
    runs-on: ubuntu-latest
    env:
      YUNO: ${{secrets.YUNO}}
      GH_TOKEN: ${{secrets.GH_TOKEN}}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Logging bot
      run: |
        bash scripts/main.sh

